
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmbywoaicmryejnhudix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtYnl3b2FpY21yeWVqbmh1ZGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTY2NTIsImV4cCI6MjA1ODc5MjY1Mn0.HpTyu6TcWR_jubtJTLS8mxC2-RDiXh-b3copX6qKZcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
